name: GCS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

jobs:
  upload-survey:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && github.repository == 'khanhnwin/sandbox'
    steps:
    - id: Checkout
      uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'storage/flutter-survey-metadata.json'
        destination: 'khanh-sandbox-bucket/'
        predefinedAcl: publicRead
    - id: 'uploaded-files'
      env:
        file: '${{ steps.upload-file.outputs.uploaded }}'
      run: echo $file
