name: survey_validator
description: |
  Small application for validating the survey
  metadata file which is used by package:unified_analytics
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  unified_analytics: ^3.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
